### ISSUE TITLE
typo in .gitignore

### ISSUE THREAD

**Issue by hirotosuzuki** [m3dev/cookiecutter-gokart#6]
https://github.com/m3dev/cookiecutter-gokart/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/.gitignore#L108

`resource`ではなく`resources`ではないでしょうか？

**Comment by hirosassa** [comment]
@hirotosuzuki ありがとうございます！おっしゃる通りだと思いますので、修正PR作成お願いできますか？

**Comment by hirosassa** [comment]
@hirotosuzuki こちらでPR作成しマージしました。ご報告ありがとうございます！
